# Generated by Django 5.2.8 on 2025-12-06 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklisttask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='checklisttask',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='checklisttask',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_tasks', to='wagtailcore.page'),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
